### PR TITLE
#452: Get correct index parameter

### PR DESCRIPTION
**Pull request by lmangani**
Potential fix for #452

### CODE REVIEW

**Comment by lmangani** [comment]
@sergibondarenko pending testing and review

**Comment by havlan** [comment]
@lmangani I think the first if statement never passes.
`if (req.fetchParams && req.fetchParams.title) {
      const index = req.fetchParams.title.toString() || req.fetchParams.title;
      $scope.indices.push(index);
    }`
I guess this is due to `req.fetchParams.title`. `req.fetchParams.title.index` ?

**Comment by lmangani** [comment]
@havlan patching, I mis-interpreted the provided example indeed

**Comment by lmangani** [comment]
thanks @havlan corrected with a backwards compatible condition (hopefully!)

**Comment by havlan** [comment]
@lmangani excellent work! :+1:

**Comment by lmangani** [comment]
@havlan did it work and solve the issue?

**Comment by havlan** [comment]
@lmangani from what I can manually test it works as intended. Thanks! [watcher.txt](https://gist.githubusercontent.com/havlan/ac06509acdae14c0ac1bd06a8751722a/raw/b9c0128a8d540733ec0439518cc7de8ac86dfc6c/working.txt)

**Comment by lmangani** [comment]
@sergibondarenko ready for merge on the next available round - thanks!

**Comment by lmangani** [comment]
@sergibondarenko does this need any backporting and/or do we know if it affects previous versions?

**Pull request merged**
