### PR TITLE
Bring back equal operator to spy wizard.

### PR DESCRIPTION
**Pull request by sergibondarenko**

### CODE REVIEW

**Comment by sergibondarenko** [comment]
@havlan you [wrote](https://github.com/sirensolutions/sentinl/pull/476) that the equal operator is limiting inside spy wizard. Why?

**Comment by havlan** [comment]
@sergibondarenko 
It all depends on the use case. If the user wishes to get an alert when the ```payload.hits.total``` reaches 100,000. It all depends on whether it queries at the exact right time.
e.g.
Query 11:10:00 - payload.hits.total = 99,851
Query 11:11:00 - payload.hits.total = 100,100
Would not hit if I understand correctly. 

This is why I think that the equals operator is confusing to have.
Given that I understand the querying correctly.

**Comment by lmangani** [comment]
@sergibondarenko we need to keep all options for this to be a programmable environment. This includes potential dead ends depending on the specific use-case or application, without excluding any.

**Comment by sergibondarenko** [comment]
@lmangani ok, I bring back the equal operator

**Pull request merged**
