### PR TITLE
Branch 5.5.1

### LINKED ISSUE #164: 5.5 Release
After building a release for 5.5.0 the plugin fails to start with the following error:-

Attempting to transfer from file:///home/osboxes/releases/sentinl-v5.5.0.zip
Transferring 88954789 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Joi.string() does not allow arguments."

Any ideas?

### PR DESCRIPTION
**Pull request by rmacd**
Fixes #164 

(known issue where the buttons do not look great now ... but functionality is OK)

### CODE REVIEW

**Comment by lmangani** [comment]
Thanks @rmacd much appreciated!

**Comment by fbaligand** [comment]
@rmacd 
Why branch/version 5.5.1 rather than 5.5.0 ?

**Comment by rmacd** [comment]
Latest version of Kibana 5.5.x is 5.5.1 ... https://github.com/elastic/kibana/tree/5.5

**Comment by fbaligand** [comment]
Yes, but it is current dev version which is not yet released : 
https://github.com/elastic/kibana/tags

**Comment by rmacd** [comment]
See #167

**Pull request merged**
