### PR TITLE
issue-419-browser-close-auth-selector-error

### PR DESCRIPTION
**Pull request by OleksandrSlobodian**
Was trying to make this different way(too many lines for such simple thing...): catching before 283 line, but unfortunately, browsers didn't close.

### CODE REVIEW

**Comment by sergibondarenko** [comment]
@OleksandrSlobodian please sign the CLA agreement and resolve the conflicts

**Comment by OleksandrSlobodian** [comment]
Signed CLA, Conflicting files is the file with changes of this PR

**Comment by sergibondarenko** [comment]
@OleksandrSlobodian please check if you signed CLA

**Comment by lmangani** [comment]
@OleksandrSlobodian could the email used in github be different from the one you used to commit?

**Comment by OleksandrSlobodian** [comment]
@lmangani - nope, same

**Comment by sergibondarenko** [comment]
@OleksandrSlobodian Try to sign in and accept the agreement with both names, one at a time.

**Comment by OleksandrSlobodian** [comment]
@sergibondarenko unfortunately, sign option is blocked (gray) for my account, already signed... so overcomplicated :S

**Comment by sergibondarenko** [comment]
@OleksandrSlobodian run the following command
```
git config user.email
```
Are you signed in with the same email?

**Comment by OleksandrSlobodian** [comment]
@sergibondarenko, nice catch!

**Comment by sergibondarenko** [comment]
@OleksandrSlobodian thank you for the fix.

**Comment by OleksandrSlobodian** [comment]
@sergibondarenko forgot to tell: you made the awesome product!

**Pull request merged**
