### PR TITLE
Support https in a proper node.js way.

### PR DESCRIPTION
**Pull request by EricSmekens**
If you want to use https, you can now:
`useHttps: true`

Fixes: #108

If this need to be switched to a different branch, let me know or just switch it.

### CODE REVIEW

**Comment by lmangani** [comment]
Thanks for the quick fix @EricSmekens we'll backport into our private

**Comment by EricSmekens** [comment]
@lmangani Could you review this again with the extra commits I made?
Made 1 fix to the PR, and also automatically set header: "Content-Length" if possible.
(Use-case, for example Microsoft Teams-webhooks require this header if doing a post).

**Comment by lmangani** [comment]
@EricSmekens Thanks, Eric!
@SergeyBondarenko could you take this for a spin?

**Comment by SergeyBondarenko** [comment]
@lmangani yes, you can.

**Comment by SergeyBondarenko** [comment]
@lmangani ok

**Pull request merged**
